---

- hosts: all
  tasks:

    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: true
      become: true

    - name: enable and start apache2
      service:
        name: apache2
        enabled: yes
        state: started
      become: true
