---

- hosts: automationservers
  become: true

  tasks:
  
    - name: Update apt
      apt:
        state: present
        update_cache: yes

    - name: Install Microsoft repository package
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb

    - name: Install Java 11 and .NET Core 3.1
      apt:
        name: "{{ item.name }}"
        update_cache: yes
      with_items:
        - name: apt-transport-https
        - name: openjdk-11-jdk
        - name: dotnet-sdk-3.1
        
    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository to apt
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        filename: jenkins
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
      
    - name: Setup Jenkins admin user and mark initial setup as complete
      template:
        src: templates/jenkins/basic-security.groovy.j2
        dest: /var/lib/jenkins/basic-security.groovy
        owner: jenkins
        group: jenkins
      notify:
        - Restart Jenkins
        - Delete user creation and skip setup script
      
    - name: Turn off Jenkins setup wizard
      lineinfile:
        dest: /etc/default/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
      notify:
        - Restart Jenkins

    - name: Start Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Wait untils Jenkins web API is available
      uri:
        url: "http://localhost:8080/cli"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 5
      delay: 10

    - name: Install Jenkins plugins
      community.general.jenkins_plugin:
        name: "{{ item.name }}"
        timeout: 120
      with_items:
        - name: git
        - name: workflow-aggregator
        - name: jackson2-api
      notify:
        - Restart Jenkins
      retries: 5
      delay: 10
        
      
  handlers:
  
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
        
    - name: Delete user creation and skip setup script
      file:
        path: /var/lib/jenkins/basic-security.groovy
        state: absent

- hosts: webservers

  tasks:

    - name: apache2 is at latest version
      apt:
        name: apache2
        state: latest
        update_cache: true
      become: true

    - name: apache2 is enabled and started
      service:
        name: apache2
        enabled: yes
        state: started
      become: true
      

